name: action (linux)

on: [pull_request]

permissions: read-all

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{github.workflow}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          rm $(which docker)
      - name: docker-image
        uses: "docker://ubuntu:22.04"
        with:
          entrypoint: bash
          args: "-c \"echo 111 >> bbb.txt\""
